### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by sfontana** [google/hyou#17]
The project is great and much faster than gspread.
I would like to use it for my projects however it seems that there's not much going on.
Are you going to maintain it in the future? When will version 3 be released?
Would be happy to contribute btw.

**Comment by nya3jp** [comment]
Due to server-side API upgrade, v3 is going to be a backward-incompatible release, and I'm redesigning Hyou API carefully. It will take more time until v3 release is released, sorry.

**Comment by sfontana** [comment]
Thanks for the update!
