### ISSUE TITLE
Why are file opened in binary mode? 

### ISSUE THREAD

**Issue by Savier** [google/hyou#2]
I think there are must be just 'r' here in hyou/client.py

```
  with open(json_path, 'rb') as f:
    json_text = f.read()
```

Besides that, 2to3 makes working module for python3.5 (One must run 2to3 to gdata and python-gflags)

**Comment by nya3jp** [comment]
I've never tried 2to3 by myself but it's good to hear it works with Python3.

I've fixed the open mode to 'r' as you pointed out. Thanks for report!
